name: ci

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 2 * * *"

jobs:
  autogreen:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
  
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Auto Commit
        run: |
          git config --local user.email "zouxiangq@qq.com"
          git config --local user.name "fxzou"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "fix issue"
          git push
